version: '2'
services:
  web: &web
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    command: rake test
    volumes:
    - .:/sdk
    volumes_from:
      - bundle_cache
    ports:
    - "8000:8000"

  bundle_cache:
    image: ruby:2.4-jessie # Should be the same as the app Dockerfile.dev base image
    volumes:
    - /usr/local/bundle